FROM golang:1.24-alpine AS builder
RUN mkdir -p /app
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY wol_proxy/main.go .
RUN go build -o wol_proxy main.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates && update-ca-certificates
RUN mkdir -p /app 
# Set the working directory
WORKDIR /app
# Copy the binary from the builder stage
COPY --from=builder /app/wol_proxy /app/wol_proxy
CMD ["/app/wol_proxy"]
